version: "3.8"
services:
  sup_server:
    env_file:
      - ./server/.env
    build: ./server
    ports:
      - "7000:4000"
    restart: on-failure
  sup_client:
    env_file:
      - ./client/.env
    build: ./client
    ports:
      - "7002:4173"
    depends_on:
      - "sup_server"
    restart: on-failure